services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
postgres:
   image: postgres:16-alpine
   restart: unless-stopped
   environment:
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: npg_kRdI0yw4bQWA
      POSTGRES_DB: neondb
   ports:
      - "5432:5432"
   volumes:
      - postgres_data:/var/lib/postgresql/data
redis:
   image: redis:7-alpine
   restart: unless-stopped
   ports:
        - "6379:6379"
volumes:
    postgres_data: